"""Render MP4 previews for analog-first teaching examples.

Uses ``ME_SUPPRESS_FADE=1`` and `disable_caching` for reproducible local checks.
Output: ``media/videos/examples/<stem>.mp4``.

Usage (repo root):
    python scripts/export_example_videos.py
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EXAMPLES = REPO / "examples"
OUT_DIR = REPO / "media" / "videos" / "examples"

os.environ.setdefault("ME_SUPPRESS_FADE", "1")

# (output stem, example path relative to examples, scene class, manim quality flag)
SCENES: tuple[tuple[str, str, str, str], ...] = (
    ("analog_01_rc_charge", "analog/01_rc_charge.py", "RCChargeScene", "medium_quality"),
    (
        "analog_02_diode_rectifier",
        "analog/02_diode_rectifier.py",
        "HalfWaveRectifierScene",
        "medium_quality",
    ),
    (
        "analog_03_cmos_inverter",
        "analog/03_cmos_inverter.py",
        "CMOSInverterScene",
        "high_quality",
    ),
    (
        "analog_04_npn_amplifier",
        "analog/04_npn_amplifier.py",
        "NPNAmplifierScene",
        "high_quality",
    ),
    (
        "analog_05_opamp_inverting",
        "analog/05_opamp_inverting.py",
        "OpAmpInvertingScene",
        "high_quality",
    ),
    (
        "analog_06_opamp_integrator",
        "analog/06_opamp_integrator.py",
        "OpAmpIntegratorScene",
        "high_quality",
    ),
    (
        "analog_07_zener_regulator",
        "analog/07_zener_regulator.py",
        "ZenerRegulatorScene",
        "high_quality",
    ),
    (
        "analog_08_rlc_transient",
        "analog/08_rlc_transient.py",
        "RLCTransientScene",
        "high_quality",
    ),
)


def _load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _render_video(scene_cls: type, cls_name: str, quality: str) -> Path:
    from manim import tempconfig

    tmpdir = tempfile.mkdtemp(prefix="me_example_video_")
    with tempconfig(
        {
            "quality": quality,
            "disable_caching": True,
            "media_dir": tmpdir,
            "write_to_movie": True,
            "save_last_frame": False,
        }
    ):
        scene_cls().render()

    matches = sorted(Path(tmpdir).rglob(f"{cls_name}*.mp4"))
    if not matches:
        raise FileNotFoundError(f"no MP4 matching {cls_name!r} under {tmpdir}")
    return matches[-1]


def main() -> None:
    os.environ["ME_SUPPRESS_FADE"] = "1"
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    from manim import __version__ as manim_version

    print(f"Manim CE {manim_version}")
    print(f"Writing videos to {OUT_DIR}\n")

    for stem, rel, cls_name, quality in SCENES:
        path = EXAMPLES / rel
        mod = _load_module(stem, path)
        scene_cls = getattr(mod, cls_name)
        print(f"  rendering {stem} ({quality})...")
        mp4 = _render_video(scene_cls, cls_name, quality)
        dest = OUT_DIR / f"{stem}.mp4"
        shutil.copy2(mp4, dest)
        print(f"    -> {dest}")

    readme = OUT_DIR / "README.md"
    readme.write_text(
        "\n".join(
            [
                "# Example acceptance videos",
                "",
                "Generated by `python scripts/export_example_videos.py`.",
                "",
                "Settings: `ME_SUPPRESS_FADE=1`, `disable_caching=True`, "
                "and per-scene quality as in the script.",
                "",
                "| File | Source |",
                "|------|--------|",
                *(f"| `{stem}.mp4` | `examples/{rel}` → `{cls}` |" for stem, rel, cls, _ in SCENES),
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"\nWrote {readme}")


if __name__ == "__main__":
    main()
