"""Export last-frame PNGs for manual review of tests/visual golden scenes.

Matches visual test settings: low_quality, ME_SUPPRESS_FADE=1, save_last_frame.

Usage (repo root):
    python scripts/export_visual_golden_previews.py

Output: tests/visual/golden/previews/*.png
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = REPO / "tests" / "visual" / "golden" / "previews"
EXAMPLES = REPO / "examples"

# Match tests/visual/conftest.py so previews are not taken mid-fade.
os.environ.setdefault("ME_SUPPRESS_FADE", "1")

# (output stem, example path relative to examples, scene class name)
DHASH_SCENES: tuple[tuple[str, str, str], ...] = (
    ("acceptance_three_layer", "basics/acceptance_three_layer.py", "AcceptanceScene"),
    ("clock_data_waveform", "basics/clock_data_waveform.py", "ClockDataWaveformDemo"),
    ("signal_chain_demo", "basics/signal_chain_demo.py", "SignalChainDemo"),
    ("spi_byte_transfer", "protocol/spi_byte_transfer.py", "SPIByteTransferDemo"),
    ("uart_byte_transfer", "protocol/uart_byte_transfer.py", "UARTByteTransferDemo"),
)


def _load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _render_scene_last_frame(scene_cls: type, glob_pattern: str) -> Path:
    from manim import tempconfig

    tmpdir = tempfile.mkdtemp(prefix="me_golden_preview_")
    with tempconfig(
        {
            "quality": "low_quality",
            "disable_caching": True,
            "media_dir": tmpdir,
            "write_to_movie": False,
            "save_last_frame": True,
        }
    ):
        scene_cls().render()

    matches = sorted(Path(tmpdir).rglob(f"{glob_pattern}*.png"))
    if not matches:
        raise FileNotFoundError(f"no PNG matching {glob_pattern!r} under {tmpdir}")
    return matches[-1]


def _render_rc_step_response_preview() -> Path:
    """Static layout frame for geometry-only golden (no example Scene)."""
    import numpy as np
    from manim import Scene, config

    mod = _load_module("rc_step_response", EXAMPLES / "analog" / "rc_step_response.py")
    from manim_engineering.renderers.minimal import ManimRenderer

    class RCStepResponsePreview(Scene):
        def construct(self) -> None:
            circuit, elements, layout = mod.build_fixture()
            pad_x, pad_y = 1.2, 0.8
            bbox = layout.scene_bbox
            config.frame_width = max(5.0, bbox.max_x - bbox.min_x + pad_x)
            config.frame_height = max(2.5, bbox.max_y - bbox.min_y + pad_y)
            mob = ManimRenderer().render(circuit, layout, elements)
            mob.shift(
                np.array(
                    [
                        -(bbox.min_x + bbox.max_x) / 2.0,
                        -(bbox.min_y + bbox.max_y) / 2.0,
                        0.0,
                    ]
                )
            )
            self.add(mob)
            self.wait(0.1)

    return _render_scene_last_frame(RCStepResponsePreview, "RCStepResponsePreview")


def main() -> None:
    os.environ["ME_SUPPRESS_FADE"] = "1"
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    from manim import __version__ as manim_version  # noqa: F401

    print(f"Manim CE {manim_version}")
    print(f"Writing previews to {OUT_DIR}\n")

    for stem, rel, cls_name in DHASH_SCENES:
        path = EXAMPLES / rel
        mod = _load_module(stem, path)
        scene_cls = getattr(mod, cls_name)
        png = _render_scene_last_frame(scene_cls, cls_name)
        dest = OUT_DIR / f"{stem}_last_frame.png"
        shutil.copy2(png, dest)
        print(f"  {dest.name}")

    rc_png = _render_rc_step_response_preview()
    rc_dest = OUT_DIR / "rc_step_response_layout_preview.png"
    shutil.copy2(rc_png, rc_dest)
    print(f"  {rc_dest.name}  (geometry golden only)")

    golden_dir = REPO / "tests" / "visual" / "golden"
    readme = OUT_DIR / "README.md"
    lines = [
        "# Visual golden preview frames",
        "",
        "Generated by `python scripts/export_visual_golden_previews.py`.",
        "Settings match `tests/visual/`: `low_quality`, `ME_SUPPRESS_FADE=1`, last frame.",
        "",
        "| PNG | Golden file(s) |",
        "|-----|----------------|",
    ]
    for stem, _, _ in DHASH_SCENES:
        lines.append(f"| `{stem}_last_frame.png` | `{stem}.dhash.txt`, `{stem}.geometry.txt` |")
    lines.append("| `rc_step_response_layout_preview.png` | `rc_step_response.geometry.txt` only |")
    lines.append("")
    lines.append("## Stored hashes (for cross-check)")
    lines.append("")
    for name in sorted(golden_dir.glob("*.txt")):
        if name.parent.name != "golden":
            continue
        value = name.read_text(encoding="utf-8").strip()
        lines.append(f"- `{name.name}`: `{value}`")
    readme.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {readme}")


if __name__ == "__main__":
    main()
